output_folder: "../logs"
dataset:
  img_folder: "../data/VOCdevkit/VOC2007/JPEGImages"
  json_folder: "../data"

model:
  backbone: resnet34
  fpn_feats_dim: 128

loader:
  batch_size: 8
  num_workers: 4

opt:
  # 1x schedule: mAP@IoU=0.5 ~61%
  warmup_epochs: 3
  epochs: 10
  learning_rate: 0.01
  

# other parameters can be specified in this yaml file
# e.g. the following lines will reset the number of training epochs to 8
#opt:
#  epochs: 8

# see config.py for more details
