output_folder: "../logs"
dataset:
  img_folder: "../data/VOCdevkit/VOC2007/JPEGImages"
  json_folder: "../data"

model:
  # backbone: resnet34
  # fpn_feats_dim: 128
  backbone: resnet152
  backbone_out_feats_dims: [512, 1024, 2048]
  fpn_feats_dim: 256

input:
  img_min_size: [736, 768, 800]
  img_max_size: 1024

loader:
  batch_size: 8
  num_workers: 16

opt:
  # 1x schedule: mAP@IoU=0.5 ~61%
  warmup_epochs: 2
  epochs: 100
  learning_rate: 0.008

test_cfg:
  score_threshold: 0.05
  

# other parameters can be specified in this yaml file
# e.g. the following lines will reset the number of training epochs to 8
#opt:
#  epochs: 8

# see config.py for more details
